services:
  - type: web
    name: farmerapp-api
    runtime: docker
    plan: free
    healthCheckPath: /api/auth/ping
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MongoDb__ConnectionString
        sync: false
      - key: MongoDb__DatabaseName
        value: farmer_app_db
      - key: Jwt__Key
        sync: false
